---
- name: Add Docker APT key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
    validate_certs: True

- name: Add Docker source
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main

- name: Install suggested Docker kernel modules
  apt:
    update_cache: True
    cache_valid_time: 300
    name: 'linux-image-extra-{{ ansible_kernel }}'
    state: present

- name: Ensure Docker is installed
  apt:
    update_cache: True
    name: docker-engine
    state: latest

- name: Create Docker group
  group:
    name: docker

- name: Start Docker daemon
  service:
    name: docker
    state: started
    enabled: True

- name: Add current user to Docker group
  user:
    append: Yes
    groups: docker
    name: "{{ ansible_user_id }}"
    state: present
 
- name: Add Docker Machine (tool)
  get_url:
    url: https://github.com/docker/machine/releases/download/v0.5.6/docker-machine_linux-amd64
    dest: /usr/local/bin/docker-machine
    owner: root
    group: root
    mode: 0755

- name: Add Docker Compose (tool)
  get_url:
    url: https://github.com/docker/compose/releases/download/1.5.2/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0755

# TODO: Add UFW changes e.g. DEFAULT_FORWARD_POLICY="ACCEPT"
# https://docs.docker.com/engine/installation/ubuntulinux/
# https://docs.ansible.com/ansible/ufw_module.html
